export const characterSeed = [
  {
    handle_id: '420',
    name: 'Mr. Okra',
    image_url: 'https://res.cloudinary.com/de0mhjdfg/image/upload/v1676852416/gnawlinzAllies/mrOkraPxl_mnfyeo.png',
    slot0: 1,
    slot1: 2,
    slot2: null,
    slot3: null,
    slot4: null,
    slot5: null,
    slot6: null,
    slot7: null,
    health: 10,
    strength: 5,
    endurance: 2,
    mood: 9,
    location: 1,
    ally_count: 0
  },
  {
    handle_id: '420',
    name: 'Morgus',
    image_url: 'https://res.cloudinary.com/de0mhjdfg/image/upload/v1676922567/gnawlinzAllies/MorgusPxl_sz0c7h.png',
    slot0: 3,
    slot1: 4,
    slot2: null,
    slot3: null,
    slot4: null,
    slot5: null,
    slot6: null,
    slot7: null,
    health: 10,
    strength: 3,
    endurance: 4,
    mood: 5,
    location: 2,
    ally_count: 0
  },
  {
    handle_id: '420',
    name: 'Morris Bart',
    image_url: 'https://res.cloudinary.com/de0mhjdfg/image/upload/v1676932653/gnawlinzAllies/MorrisBartPxl_mhl3tg.png',
    slot0: 5,
    slot1: 6,
    slot2: null,
    slot3: null,
    slot4: null,
    slot5: null,
    slot6: null,
    slot7: null,
    health: 10,
    strength: 1,
    endurance: 2,
    mood: 4,
    location: 3,
    ally_count: 0
  }
];
