export const choiceSeed = [
  { //fight jet
    flavor_text0: 'You stand you ground and are engaged by a Lockheed Martin F-35 Lightning II.',
    flavor_text1: '',
    story_effect: null,
    enemy_effect: 2,
    ally_effect: null,
    item_effect: null,
   },
   { // fight ZB
    flavor_text0: 'You attack the banana zombie!',
    flavor_text1: 'You defeated the banana zombie. It lies limp on the ground.',
    story_effect: null,
    enemy_effect: 1,
    ally_effect: null,
    item_effect: null,
   },
   { //talk to jet
    flavor_text0: 'You wave your hand to get the attention of the flying object.  The object lows and hovers above you, revealing itself as a Lockheed Martin F-35 Lightning II.',
    flavor_text1: 'The pilot responds by opening up the canopy of his vehicle and tossing out a care package of supplies!  Wordlessly, he reseals the cockpit and flies off into the distance.',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: 1,
   },
   { //talk to ZB
    flavor_text0: 'You attempt to make contact with the entity.  Is slides grotesquely toward you with, gritting its bared teeth.  It responds to you only with a low growl and violence.',
    flavor_text1: '',
    story_effect: null,
    enemy_effect: 1,
    ally_effect: null,
    item_effect: null,
   },
   { // fail jet stealth
    flavor_text0: 'You attempt to stick to the shadows, but the advanced detections systems of the F-35 Lightning II easily track you!',
    flavor_text1: '',
    story_effect: null,
    enemy_effect: 2,
    ally_effect: null,
    item_effect: null,
   },
   { // pass ZB stealth
    flavor_text0: 'You attempt to explore the area without disturbing the entity.',
    flavor_text1: 'You slink around the area like a shadow, deftly avoiding the gaze of the entity. You found supplies!',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: 1,
   },
   { // Flee
    flavor_text0: 'You wordlessly turn and sprint away from the area.  Whatever you might find here is not worth a potentially deadly fight.',
    flavor_text1: '',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: null,
   },
   { // Hide and Rest
    flavor_text0: 'You go inside, and find an abandoned space. You close and barricade the door once you\'ve looked around long enough to be sure you\'re alone.',
    flavor_text1: 'You rest for a while and get your strength back.',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: null,
   },
   { // Search for survivors 
    flavor_text0: 'You cautiously enter the space and call out for survivors. You hear the response of a living person! The developers haven\'t implemented allies yet, so you receive a consolation item!',
    flavor_text1: 'You\'re confident you have found everything there is to find here, time to move on.',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: 1,
   },
   { // Search for supplies
    flavor_text0: 'You cautiously enter the space and search it for anything of use. The space seems like it\'s been picked mostly clean, but you do find one item worth taking with you.',
    flavor_text1: 'You\'re confident you have found everything there is to find here, time to move on.',
    story_effect: null,
    enemy_effect: null,
    ally_effect: null,
    item_effect: 2,
   }
];

